cube:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: x_wheel_joint
    pid: {p: 1.0, i: 0.01, d: 0.0}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: y_wheel_joint
    pid: {p: 1.0, i: 0.01, d: 0.0}
  joint3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: z_wheel_joint
    pid: {p: 1.0, i: 0.01, d: 0.0}